# Launch EC2 instance in public subnet
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  NetworkStackName:
    Type: "String"
    Default: network
  DatabaseStackName:
    Type: String
    Default: db1
  ImageId:
    Type: String
    Default: ami-0a485299eeb98b979
    AllowedValues: [ami-05c13eab67c5d8861, ami-0a485299eeb98b979]
    ConstraintDescription: must select a valid ami specific to your region.
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
      t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
      m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
      c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
Resources:
  WebKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: WebKeyPair

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref WebKeyPair
      SecurityGroupIds:
      - Fn::ImportValue: !Sub "${DatabaseStackName}-WebSecurityGroupId"
      SubnetId:
      - Fn::ImportValue: !Sub "${NetworkStackName}-PublicSubnet-A"

# Output shall be DNS name of the EC2
