AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Type: String
    Description: Bucket Name
    Default: cnf-suite-claims


Resources:
  LoggingBucket:
    Type: 'AWS::S3::Bucket'
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LoggingBucket
                - /*
            Condition:
              ArnLike:
                'aws:SourceArn': !GetAtt
                  - S3Bucket
                  - Arn
              StringEquals:
                'aws:SourceAccount': !Sub '${AWS::AccountId}'

  S3Bucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Description: CNF S3 Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - Id: DeleteContentAfter180Days
          Status: Enabled
          ExpirationInDays: 180
        - Id: DeleteContentAfter1Day
          Prefix: 'qe/'
          Status: Enabled
          ExpirationInDays: 1
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: cnf-access-logs
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-cnf" ]]
      - Key: Owner
        Value: cnf
      - Key: Environment
        Value: production
  S3User:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: bucket-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/*

  S3UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3User

Outputs:

  LogBucketName:
    Description: Name of the access log bucket
    Value: !Ref LoggingBucket

  S3BucketName:
    Value: !Ref S3Bucket
    Description: Name of the CNF S3 bucket

  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: Domain Name of the CNF S3 bucket

  S3User:
    Value: !Ref S3User
    Description: S3 user to access the bucket

  AccessKeyID:
    Value: !Ref S3UserAccessKey

  SecretAccessKey:
    Value: !GetAtt S3UserAccessKey.SecretAccessKey
